/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class t_mall_spu_attr {
    getFieldTypeMap() {
        let fieldTypeMap = new Map();
        fieldTypeMap.set('attr_id', 'Long');
        fieldTypeMap.set('attr_vals', 'String');
        fieldTypeMap.set('spu_id', 'Long');
        fieldTypeMap.set('name', 'String');
        fieldTypeMap.set('desc', 'String');
        fieldTypeMap.set('type', 'Integer');
        fieldTypeMap.set('create_time', 'Date');
        fieldTypeMap.set('update_time', 'Date');
        return fieldTypeMap;
    }

    getClassName() {
        return 't_mall_spu_attr';
    }

    getPrimaryKeyList() {
        let primaryKeyList = [];
        primaryKeyList.push('attr_id');
        return primaryKeyList;
    }

    getIndexList() {
        let indexList = [];
        return indexList;
    }

    getEncryptedFieldList() {
        let encryptedFieldList = [];
        return encryptedFieldList;
    }

    setAttr_id(attr_id) {
        this.attr_id = attr_id;
    }

    getAttr_id() {
        return this.attr_id;
    }

    setAttr_vals(attr_vals) {
        this.attr_vals = attr_vals;
    }

    getAttr_vals() {
        return this.attr_vals;
    }

    setSpu_id(spu_id) {
        this.spu_id = spu_id;
    }

    getSpu_id() {
        return this.spu_id;
    }

    setName(name) {
        this.name = name;
    }

    getName() {
        return this.name;
    }

    setDesc(desc) {
        this.desc = desc;
    }

    getDesc() {
        return this.desc;
    }

    setType(type) {
        this.type = type;
    }

    getType() {
        return this.type;
    }

    setCreate_time(create_time) {
        this.create_time = create_time;
    }

    getCreate_time() {
        return this.create_time;
    }

    setUpdate_time(update_time) {
        this.update_time = update_time;
    }

    getUpdate_time() {
        return this.update_time;
    }
}

module.exports = {t_mall_spu_attr}