/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class t_mall_shopcart {
    getFieldTypeMap() {
        let fieldTypeMap = new Map();
        fieldTypeMap.set('sc_id', 'Long');
        fieldTypeMap.set('spu_attrs', 'String');
        fieldTypeMap.set('uid', 'Long');
        fieldTypeMap.set('spu_id', 'Long');
        fieldTypeMap.set('quantity', 'Integer');
        fieldTypeMap.set('price', 'Float');
        fieldTypeMap.set('selected', 'Integer');
        fieldTypeMap.set('create_time', 'Date');
        fieldTypeMap.set('update_time', 'Date');
        return fieldTypeMap;
    }

    getClassName() {
        return 't_mall_shopcart';
    }

    getPrimaryKeyList() {
        let primaryKeyList = [];
        primaryKeyList.push('sc_id');
        return primaryKeyList;
    }

    getIndexList() {
        let indexList = [];
        return indexList;
    }

    getEncryptedFieldList() {
        let encryptedFieldList = [];
        return encryptedFieldList;
    }

    setSc_id(sc_id) {
        this.sc_id = sc_id;
    }

    getSc_id() {
        return this.sc_id;
    }

    setSpu_attrs(spu_attrs) {
        this.spu_attrs = spu_attrs;
    }

    getSpu_attrs() {
        return this.spu_attrs;
    }

    setUid(uid) {
        this.uid = uid;
    }

    getUid() {
        return this.uid;
    }

    setSpu_id(spu_id) {
        this.spu_id = spu_id;
    }

    getSpu_id() {
        return this.spu_id;
    }

    setQuantity(quantity) {
        this.quantity = quantity;
    }

    getQuantity() {
        return this.quantity;
    }

    setPrice(price) {
        this.price = price;
    }

    getPrice() {
        return this.price;
    }

    setSelected(selected) {
        this.selected = selected;
    }

    getSelected() {
        return this.selected;
    }

    setCreate_time(create_time) {
        this.create_time = create_time;
    }

    getCreate_time() {
        return this.create_time;
    }

    setUpdate_time(update_time) {
        this.update_time = update_time;
    }

    getUpdate_time() {
        return this.update_time;
    }
}

module.exports = {t_mall_shopcart}