/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class t_mall_order {
    getFieldTypeMap() {
        let fieldTypeMap = new Map();
        fieldTypeMap.set('order_id', 'Long');
        fieldTypeMap.set('uid', 'Long');
        fieldTypeMap.set('spu_id', 'Long');
        fieldTypeMap.set('spu_num', 'Integer');
        fieldTypeMap.set('status', 'Integer');
        fieldTypeMap.set('order_time', 'Date');
        fieldTypeMap.set('pay_time', 'Date');
        fieldTypeMap.set('amount', 'Float');
        fieldTypeMap.set('create_time', 'Date');
        fieldTypeMap.set('update_time', 'Date');
        fieldTypeMap.set('spu_attrs', 'String');
        return fieldTypeMap;
    }

    getClassName() {
        return 't_mall_order';
    }

    getPrimaryKeyList() {
        let primaryKeyList = [];
        primaryKeyList.push('order_id');
        return primaryKeyList;
    }

    getIndexList() {
        let indexList = [];
        return indexList;
    }

    getEncryptedFieldList() {
        let encryptedFieldList = [];
        return encryptedFieldList;
    }

    setOrder_id(order_id) {
        this.order_id = order_id;
    }

    getOrder_id() {
        return this.order_id;
    }

    setUid(uid) {
        this.uid = uid;
    }

    getUid() {
        return this.uid;
    }

    setSpu_id(spu_id) {
        this.spu_id = spu_id;
    }

    getSpu_id() {
        return this.spu_id;
    }

    setSpu_num(spu_num) {
        this.spu_num = spu_num;
    }

    getSpu_num() {
        return this.spu_num;
    }

    setStatus(status) {
        this.status = status;
    }

    getStatus() {
        return this.status;
    }

    setOrder_time(order_time) {
        this.order_time = order_time;
    }

    getOrder_time() {
        return this.order_time;
    }

    setPay_time(pay_time) {
        this.pay_time = pay_time;
    }

    getPay_time() {
        return this.pay_time;
    }

    setAmount(amount) {
        this.amount = amount;
    }

    getAmount() {
        return this.amount;
    }

    setCreate_time(create_time) {
        this.create_time = create_time;
    }

    getCreate_time() {
        return this.create_time;
    }

    setUpdate_time(update_time) {
        this.update_time = update_time;
    }

    getUpdate_time() {
        return this.update_time;
    }

    setSpu_attrs(spu_attrs) {
        this.spu_attrs = spu_attrs;
    }

    getSpu_attrs() {
        return this.spu_attrs;
    }
}

module.exports = {t_mall_order}