/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class t_mall_sku {
    getFieldTypeMap() {
        let fieldTypeMap = new Map();
        fieldTypeMap.set('sku_id', 'Long');
        fieldTypeMap.set('spu_id', 'Long');
        fieldTypeMap.set('name', 'String');
        fieldTypeMap.set('pic_url', 'String');
        fieldTypeMap.set('status', 'Integer');
        fieldTypeMap.set('price', 'Float');
        fieldTypeMap.set('weight', 'Float');
        fieldTypeMap.set('volume', 'Float');
        fieldTypeMap.set('attrs', 'String');
        fieldTypeMap.set('create_time', 'Date');
        fieldTypeMap.set('update_time', 'Date');
        return fieldTypeMap;
    }

    getClassName() {
        return 't_mall_sku';
    }

    getPrimaryKeyList() {
        let primaryKeyList = [];
        primaryKeyList.push('sku_id');
        return primaryKeyList;
    }

    getIndexList() {
        let indexList = [];
        return indexList;
    }

    getEncryptedFieldList() {
        let encryptedFieldList = [];
        return encryptedFieldList;
    }

    setSku_id(sku_id) {
        this.sku_id = sku_id;
    }

    getSku_id() {
        return this.sku_id;
    }

    setSpu_id(spu_id) {
        this.spu_id = spu_id;
    }

    getSpu_id() {
        return this.spu_id;
    }

    setName(name) {
        this.name = name;
    }

    getName() {
        return this.name;
    }

    setPic_url(pic_url) {
        this.pic_url = pic_url;
    }

    getPic_url() {
        return this.pic_url;
    }

    setStatus(status) {
        this.status = status;
    }

    getStatus() {
        return this.status;
    }

    setPrice(price) {
        this.price = price;
    }

    getPrice() {
        return this.price;
    }

    setWeight(weight) {
        this.weight = weight;
    }

    getWeight() {
        return this.weight;
    }

    setVolume(volume) {
        this.volume = volume;
    }

    getVolume() {
        return this.volume;
    }

    setAttrs(attrs) {
        this.attrs = attrs;
    }

    getAttrs() {
        return this.attrs;
    }

    setCreate_time(create_time) {
        this.create_time = create_time;
    }

    getCreate_time() {
        return this.create_time;
    }

    setUpdate_time(update_time) {
        this.update_time = update_time;
    }

    getUpdate_time() {
        return this.update_time;
    }
}

module.exports = {t_mall_sku}