/*
 * Copyright 2020. Huawei Technologies Co., Ltd. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class Constants {
  static readonly WIDTH_QUARTER = '25%';
  static readonly WIDTH_FULL = '100%';
  static readonly WIDTH_NEAR_FULL = '98%';
  static readonly HIGH_FULL = '100%';
  static readonly HIGH_HALF = '50%';
  static readonly WIDTH_HALF = '50%';
  static readonly HIGH_TWO_THIRD_FULL = '60%';
  static readonly WIDTH_TWO_THIRD_FULL = '60%';
  static readonly CORNER_MARK = 20;
  static readonly HIGH_OPERATION = 100;
  static readonly BUTTON_WIDTH = 120;
  static readonly BUTTON_HIGH = 30;
  static readonly PRICE_WIDTH = 160;
  static readonly GOODITEM_HIGH = 250;
  static readonly VERSION_HIGH = 300;
  static readonly SETTINGITEM_HIGH = '6%';
  static readonly CONTENT_HIGH = '94%';
  static readonly ADDRESS_HIGH = '88%';
  static readonly ADDRESS_WIDTH = '90%';
  static readonly ADDRESS_TEXT_WIDTH = 70;
  static readonly ADDRESS_TEXT_HIGH = 60;
  static readonly GOODDETAIL_TEXT_WIDTH = 54;
  static readonly DEFAULT_ADDRESS_WIDTH = 120;
  static readonly DETAIL_BUTTON_WIDTH = 180;
  static readonly BACK_POSITION = 12;
  static readonly SEARCH_HIGH = 36;
  static readonly ORDERITEM_HIGH = '10%';
  static readonly ORDER_TEXT_WIDTH = 80;
  static readonly ORDER_ADDRESS_WIDTH = 360;
  static readonly ORDER_DETAIL_HIGH = '40%';
}