/*
 * Copyright 2020. Huawei Technologies Co., Ltd. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const MenuObj = [
  {
    value: 0,
    imgUrl: $r('app.media.home'),
    title: '首页'
  },
  {
    value: 1,
    imgUrl: $r('app.media.tab_cart'),
    title: '购物车'
  },
  {
    value: 2,
    imgUrl: $r('app.media.message'),
    title: '消息'
  },
  {
    value: 3,
    imgUrl: $r('app.media.mine'),
    title: '我的'
  }
]

export const OrderText = [
  {
    value: -1,
    title: '全部',
  },
  {
    value: 0,
    title: '待付款',
  },
  {
    value: 1,
    title: '待发货',
  },
  {
    value: 2,
    title: '待收货',
  },
  {
    value: 3,
    title: '待评价',
  }
]