/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class t_mall_spu {
    getFieldTypeMap() {
        let fieldTypeMap = new Map();
        fieldTypeMap.set('spu_id', 'Long');
        fieldTypeMap.set('name', 'String');
        fieldTypeMap.set('desc', 'String');
        fieldTypeMap.set('price', 'Float');
        fieldTypeMap.set('pic_url', 'String');
        fieldTypeMap.set('remark', 'String');
        fieldTypeMap.set('status', 'Integer');
        fieldTypeMap.set('category_id', 'Long');
        fieldTypeMap.set('brand_id', 'Long');
        fieldTypeMap.set('update_time', 'Date');
        fieldTypeMap.set('create_time', 'Date');
        return fieldTypeMap;
    }

    getClassName() {
        return 't_mall_spu';
    }

    getPrimaryKeyList() {
        let primaryKeyList = [];
        primaryKeyList.push('spu_id');
        return primaryKeyList;
    }

    getIndexList() {
        let indexList = [];
        return indexList;
    }

    getEncryptedFieldList() {
        let encryptedFieldList = [];
        return encryptedFieldList;
    }

    setSpu_id(spu_id) {
        this.spu_id = spu_id;
    }

    getSpu_id() {
        return this.spu_id;
    }

    setName(name) {
        this.name = name;
    }

    getName() {
        return this.name;
    }

    setDesc(desc) {
        this.desc = desc;
    }

    getDesc() {
        return this.desc;
    }

    setPrice(price) {
        this.price = price;
    }

    getPrice() {
        return this.price;
    }

    setPic_url(pic_url) {
        this.pic_url = pic_url;
    }

    getPic_url() {
        return this.pic_url;
    }

    setRemark(remark) {
        this.remark = remark;
    }

    getRemark() {
        return this.remark;
    }

    setStatus(status) {
        this.status = status;
    }

    getStatus() {
        return this.status;
    }

    setCategory_id(category_id) {
        this.category_id = category_id;
    }

    getCategory_id() {
        return this.category_id;
    }

    setBrand_id(brand_id) {
        this.brand_id = brand_id;
    }

    getBrand_id() {
        return this.brand_id;
    }

    setUpdate_time(update_time) {
        this.update_time = update_time;
    }

    getUpdate_time() {
        return this.update_time;
    }

    setCreate_time(create_time) {
        this.create_time = create_time;
    }

    getCreate_time() {
        return this.create_time;
    }
}

module.exports = {t_mall_spu}