/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2022-2022. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class BookInfo {
    constructor() {
        this.id = undefined;
        this.bookName = undefined;
        this.author = undefined;
        this.price = undefined;
        this.publisher = undefined;
        this.publishTime = undefined;
        this.shadowFlag = undefined;
        this.imageUrl = undefined;
        this.description = undefined;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setBookName(bookName) {
        this.bookName = bookName;
    }

    getBookName() {
        return this.bookName;
    }

    setAuthor(author) {
        this.author = author;
    }

    getAuthor() {
        return this.author;
    }

    setPrice(price) {
        this.price = price;
    }

    getPrice() {
        return this.price;
    }

    setPublisher(publisher) {
        this.publisher = publisher;
    }

    getPublisher() {
        return this.publisher;
    }

    setPublishTime(publishTime) {
        this.publishTime = publishTime;
    }

    getPublishTime() {
        return this.publishTime;
    }

    setShadowFlag(shadowFlag) {
        this.shadowFlag = shadowFlag;
    }

    getShadowFlag() {
        return this.shadowFlag;
    }

    setImageUrl(imageUrl) {
        this.imageUrl = imageUrl;
    }

    getImageUrl() {
        return this.imageUrl;
    }

    setDescription(description) {
        this.description = description;
    }

    getDescription() {
        return this.description;
    }
}

BookInfo.className = 'BookInfo';

export {BookInfo}